### PR TITLE
AtLeast, AtMost #197

### PR DESCRIPTION
**Pull request by dioxmio**
As requested doing issue 197 as it might come hand for my personal projects

### CODE REVIEW

**Comment by megawac** [comment]
I think this would be better implemented through composition of methods

Count(arr, fn)
Equal(val)
Gt(val)
Lt(val)

**Comment by dioxmio** [comment]
I've updated the code according to your changes @megawac

**Comment by dioxmio** [comment]
@megawac could you check please? thanks

**Review by jgonggrijp — CHANGES_REQUESTED** [review]
@dioxmio This looks good to me. However, it seems that you edited `index.html` directly instead of `docs/index.md`. Would you mind copying your changes from the former to the latter, so that your documentation will not disappear the next time someone runs `grunt tocdoc`?

If you prefer, I can also take it from here, in which case you will still get the credit for the work you have already done.

**Pull request merged**
